import { AlertStore } from '../../../../libs/core/src';
import { AlertProvider } from '../../../../libs/react-alertx/src';
import { Inter } from 'next/font/google';
import StyledJsxRegistry from './registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledJsxRegistry>
        <body>{children}</body>
      </StyledJsxRegistry>
    </html>
  );
}
